// ============================================================
// Migration script — import ONLY 2026 data from the original
// SQLite databases into Supabase.
//
// Behavior:
//   1. Deletes ALL existing rows from every table in the Supabase
//      DB (public + uds schemas) and clears the uds-labels Storage
//      bucket, so the DB is clean before migrating.
//   2. Migrates only 2026 data:
//        - Lookup tables (no date): all rows
//        - tblSenaraiUbat:      only meds referenced by 2026 records
//        - tblSenaraiPrabungkus: only records with tarikh in 2026
//        - uds.tblNamaUbat:     only meds referenced by 2026 labels
//        - uds.tblRekodLabel:   only records with Tarikh in 2026
//   3. Sets year-scoped running numbers for 2026 and the default
//      admin password.
//
// Identity columns are `generated by default as identity`, so explicit
// ID values are preserved (matching the original IDs).
//
// Usage:
//   SUPABASE_URL=... SUPABASE_SERVICE_ROLE_KEY=... \
//   PREPACK_DB=prepack_webapp.db UDS_DB=labeluds.db \
//   npx tsx supabase/migrate-2026.ts
// ============================================================

import { createClient } from "@supabase/supabase-js";
import { readFileSync, existsSync } from "node:fs";
import { randomBytes, pbkdf2Sync } from "node:crypto";
import initSqlJs, { type Database } from "sql.js";

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const PREPACK_DB = process.env.PREPACK_DB ?? "prepack_webapp.db";
const UDS_DB = process.env.UDS_DB ?? "labeluds.db";

const TARGET_YEAR = "2026";

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}

const admin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

// ---------- Helpers ----------

function hashPassword(password: string): string {
  const salt = randomBytes(16);
  const hash = pbkdf2Sync(password, salt, 1000, 64, "sha512");
  return `${salt.toString("hex")}:${hash.toString("hex")}`;
}

async function openSqlite(dbPath: string): Promise<Database> {
  const SQL = await initSqlJs();
  return new SQL.Database(readFileSync(dbPath));
}

function readAll(db: Database, sql: string): Record<string, unknown>[] {
  const stmt = db.prepare(sql);
  const rows: Record<string, unknown>[] = [];
  while (stmt.step()) rows.push(stmt.getAsObject() as Record<string, unknown>);
  stmt.free();
  return rows;
}

async function insertRows(
  table: string,
  rows: Record<string, unknown>[],
): Promise<void> {
  if (rows.length === 0) {
    console.log(`  [${table}] 0 rows`);
    return;
  }
  // Insert in chunks to stay comfortably within header/payload limits.
  const CHUNK = 200;
  let inserted = 0;
  for (let i = 0; i < rows.length; i += CHUNK) {
    const chunk = rows.slice(i, i + CHUNK);
    const { error } = await admin.from(table).insert(chunk);
    if (error) {
      console.error(`  [${table}] FAILED: ${error.message}`);
      return;
    }
    inserted += chunk.length;
  }
  console.log(`  [${table}] inserted ${inserted} rows (IDs preserved)`);
}

async function deleteAll(table: string, pkColumn = "ID"): Promise<void> {
  // Fetch all primary keys, then delete in batches (handles tables
  // without an ID column, e.g. tblSystemSettings uses settingKey).
  const { data: rows, error: selErr } = await admin
    .from(table)
    .select(pkColumn);
  if (selErr) {
    console.error(`  [${table}] select failed: ${selErr.message}`);
    return;
  }
  if (!rows || rows.length === 0) {
    console.log(`  [${table}] already empty`);
    return;
  }
  const keys = (rows as unknown as Record<string, unknown>[]).map(
    (r) => r[pkColumn] as string | number,
  );
  const CHUNK = 200;
  let ok = 0;
  for (let i = 0; i < keys.length; i += CHUNK) {
    const chunkKeys = keys.slice(i, i + CHUNK);
    const { error } = await admin.from(table).delete().in(pkColumn, chunkKeys);
    if (error) {
      console.error(`  [${table}] delete failed: ${error.message}`);
      return;
    }
    ok += chunkKeys.length;
  }
  console.log(`  [${table}] cleared ${ok} rows`);
}

// ---------- Main ----------

async function main() {
  // 1. Clear existing data (FK-safe order: children before parents).
  console.log("=== Clearing existing Supabase data ===");
  await deleteAll("tblSenaraiPrabungkus");
  await deleteAll("tblSenaraiUbat");
  await deleteAll("tblJenisWorksheet");
  await deleteAll("tblJenisLabel");
  await deleteAll("tblKategoriUbat");
  await deleteAll("tblUnitSKU");
  await deleteAll("tblUnitPKU");
  await deleteAll("tblSystemSettings", "settingKey");
  await deleteAll("tblColorSchemes");
  await deleteAll("uds.tblRekodLabel");
  await deleteAll("uds.tblNamaUbat");

  // Clear Storage cache bucket objects (best-effort).
  try {
    const { data: files } = await admin.storage.from("uds-labels").list();
    if (files && files.length > 0) {
      await admin.storage.from("uds-labels").remove(files.map((f) => f.name));
      console.log("  [uds-labels] cleared cached PDFs");
    }
  } catch {
    console.log("  [uds-labels] bucket absent — nothing to clear");
  }

  if (!existsSync(PREPACK_DB) || !existsSync(UDS_DB)) {
    console.error(`Missing SQLite files: ${PREPACK_DB} / ${UDS_DB}`);
    process.exit(1);
  }

  const prepackDb = await openSqlite(PREPACK_DB);
  const udsDb = await openSqlite(UDS_DB);

  // 2. Lookup tables (no date filter) — migrate all rows.
  console.log("\n=== Migrating lookup tables (all rows) ===");
  await insertRows("tblJenisLabel", readAll(prepackDb, "SELECT * FROM tblJenisLabel"));
  await insertRows("tblJenisWorksheet", readAll(prepackDb, "SELECT * FROM tblJenisWorksheet"));
  await insertRows("tblKategoriUbat", readAll(prepackDb, "SELECT * FROM tblKategoriUbat"));
  await insertRows("tblUnitSKU", readAll(prepackDb, "SELECT * FROM tblUnitSKU"));
  await insertRows("tblUnitPKU", readAll(prepackDb, "SELECT * FROM tblUnitPKU"));

  // 3. tblSenaraiUbat — only meds referenced by 2026 records.
  console.log("\n=== Migrating medications referenced by 2026 records ===");
  const ubatIds = readAll(
    prepackDb,
    `SELECT DISTINCT idUbat AS id FROM tblSenaraiPrabungkus
     WHERE substr(tarikh,1,4)='${TARGET_YEAR}' AND idUbat IS NOT NULL`,
  ).map((r) => r.id as number);
  await insertReferencedMeds(prepackDb, ubatIds);

  // 4. tblSenaraiPrabungkus — 2026 records only.
  console.log("\n=== Migrating 2026 prepack records ===");
  const prabungkusRows = readAll(
    prepackDb,
    `SELECT * FROM tblSenaraiPrabungkus WHERE substr(tarikh,1,4)='${TARGET_YEAR}'`,
  );
  await insertRows("tblSenaraiPrabungkus", prabungkusRows);

  // 5. uds.tblNamaUbat — only meds referenced by 2026 labels.
  console.log("\n=== Migrating UDS meds referenced by 2026 labels ===");
  const namaUbatIds = readAll(
    udsDb,
    `SELECT DISTINCT "NamaUbatID" AS id FROM tblRekodLabel
     WHERE substr("Tarikh",1,4)='${TARGET_YEAR}' AND "NamaUbatID" IS NOT NULL`,
  ).map((r) => r.id as number);
  await insertReferencedUdsMeds(udsDb, namaUbatIds);

  // 6. uds.tblRekodLabel — 2026 records only.
  console.log("\n=== Migrating 2026 UDS labels ===");
  const rekodRows = readAll(
    udsDb,
    `SELECT "ID","Tarikh","Rujukan","NamaUbat","Kekuatan","Kelompok","Luput","Kuantiti","Penyedia","LuputNormalized","NamaUbatID"
     FROM tblRekodLabel WHERE substr("Tarikh",1,4)='${TARGET_YEAR}'`,
  );
  await insertRows("uds.tblRekodLabel", rekodRows);

  // 7. tblSystemSettings — year-scoped running numbers + defaults.
  console.log("\n=== Setting year-scoped running numbers ===");
  const maxPrepack = Math.max(
    ...prabungkusRows.map((r) => {
      const m = /^PP-(\d{4})\//.exec((r.idPrabungkus as string) || "");
      return m ? parseInt(m[1], 10) : 0;
    }),
    0,
  );
  const maxUds = Math.max(
    ...rekodRows.map((r) => {
      const m = /^UDS-(\d{4})\//.exec((r.Rujukan as string) || "");
      return m ? parseInt(m[1], 10) : 0;
    }),
    0,
  );

  const settings: { settingKey: string; settingValue: string }[] = [
    { settingKey: `running_number_${TARGET_YEAR}`, settingValue: String(maxPrepack + 1) },
    { settingKey: `running_number_uds_${TARGET_YEAR}`, settingValue: String(maxUds + 1) },
    { settingKey: "admin_password", settingValue: hashPassword("farmasi456") },
    { settingKey: "color_scheme", settingValue: "light" },
  ];
  const { error: settingsErr } = await admin.from("tblSystemSettings").insert(settings);
  if (settingsErr) {
    console.error(`  [tblSystemSettings] FAILED: ${settingsErr.message}`);
  } else {
    console.log("  [tblSystemSettings] set running numbers + defaults");
    console.log(`    running_number_${TARGET_YEAR} = ${maxPrepack + 1}`);
    console.log(`    running_number_uds_${TARGET_YEAR} = ${maxUds + 1}`);
    console.log("    admin_password = farmasi456 (default)");
    console.log("    color_scheme = light");
  }

  prepackDb.close();
  udsDb.close();
  console.log("\nMigration complete.");
}

// ---------- Referenced-med helpers (parameterized reads) ----------

async function insertReferencedMeds(
  db: Database,
  ids: number[],
): Promise<void> {
  if (ids.length === 0) {
    console.log("  [tblSenaraiUbat] 0 rows");
    return;
  }
  const rows: Record<string, unknown>[] = [];
  // Read each referenced med by id (avoids building a huge IN clause).
  for (const id of ids) {
    const stmt = db.prepare('SELECT * FROM tblSenaraiUbat WHERE "ID" = ?');
    stmt.bind([id]);
    if (stmt.step()) rows.push(stmt.getAsObject() as Record<string, unknown>);
    stmt.free();
  }
  await insertRows("tblSenaraiUbat", rows);
}

async function insertReferencedUdsMeds(
  db: Database,
  ids: number[],
): Promise<void> {
  if (ids.length === 0) {
    console.log("  [uds.tblNamaUbat] 0 rows");
    return;
  }
  const rows: Record<string, unknown>[] = [];
  for (const id of ids) {
    const stmt = db.prepare('SELECT "ID","Nama","Kekuatan" FROM tblNamaUbat WHERE "ID" = ?');
    stmt.bind([id]);
    if (stmt.step()) rows.push(stmt.getAsObject() as Record<string, unknown>);
    stmt.free();
  }
  await insertRows("uds.tblNamaUbat", rows);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
