-- ============================================================
-- Sistem Pengurusan Prabungkus Ubat — Modernization
-- Consolidated Supabase schema (single file)
-- Replaces migrations 00001..00006.
--
-- Contains: public schema + uds schema + RLS policies + seed data +
-- transactional ID-reservation RPC functions + auth rate-limit table.
--
-- Idempotent: safe to re-run (tables dropped/recreated in FK order,
-- policies dropped before re-create, functions are `create or replace`).
--
-- NOTE: Wiping tables on re-run is intentional — data is re-imported
-- by supabase/migrate-2026.ts.
-- ============================================================

-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- SECTION 1: public schema (mirrors prepack_webapp.db)
-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

-- Reset tables (reverse FK order) for clean re-runs.
drop table if exists public.tblSenaraiPrabungkus cascade;
drop table if exists public.tblSenaraiUbat cascade;
drop table if exists public.tblColorSchemes cascade;
drop table if exists public.tblSystemSettings cascade;
drop table if exists public.tblJenisWorksheet cascade;
drop table if exists public.tblJenisLabel cascade;
drop table if exists public.tblKategoriUbat cascade;
drop table if exists public.tblUnitSKU cascade;
drop table if exists public.tblUnitPKU cascade;

-- Lookup / reference tables
create table public.tblJenisLabel (
  "ID"             bigint generated by default as identity primary key,
  deskripsiLabel   text not null,
  namaFail         text not null
);

create table public.tblJenisWorksheet (
  "ID"                 bigint generated by default as identity primary key,
  deskripsiWorksheet   text not null,
  namaFail             text not null
);

create table public.tblKategoriUbat (
  "ID"     bigint generated by default as identity primary key,
  nama     text not null,
  prefix   text not null
);

create table public.tblUnitSKU (
  "ID"   bigint generated by default as identity primary key,
  nama   text not null
);

create table public.tblUnitPKU (
  "ID"   bigint generated by default as identity primary key,
  nama   text not null
);

create table public.tblSystemSettings (
  settingKey    text primary key,
  settingValue  text not null
);

create table public.tblColorSchemes (
  "ID"        bigint generated by default as identity primary key,
  schemeId    text not null unique,
  name        text not null,
  colors      text not null,          -- JSON array of 5 hex colors
  css         text not null,          -- JSON object of CSS variables
  isBuiltIn   integer default 0
);

-- Medication master
create table public.tblSenaraiUbat (
  "ID"                  bigint generated by default as identity primary key,
  deskripsiPrabungkus   text,
  namaUbat              text not null,
  namaDagangan          text,
  kategoriUbat          text not null,
  unitSKU               text,
  unitPKU               text,
  harga                 double precision,
  saizPek               double precision default 0,
  pengilang             text,
  nomborMAL             text,
  arahanTambahan        text,
  jangkaHayat           integer default 0,
  jenisLabel            bigint references public.tblJenisLabel("ID"),
  jenisWorksheet        bigint references public.tblJenisWorksheet("ID")
);

create index if not exists idx_ubat_kategori on public.tblSenaraiUbat(kategoriUbat);

-- Prepack records
create table public.tblSenaraiPrabungkus (
  "ID"                        bigint generated by default as identity primary key,
  idUbat                      bigint,                    -- soft ref (no FK, matching original)
  namaUbat                    text not null,             -- denormalized snapshot
  tarikh                      text not null,             -- 'YYYY-MM-DD'
  idPrabungkus                text not null unique,      -- 'PP-NNNN/YY-X'
  namaDagangan                text,
  nomborKelompok              text,
  tarikhLuputAsal             text,
  tarikhLuputBaharu           text,
  pengilang                   text,
  nomborMAL                   text,
  kuantitiUntukDiprabungkus   integer,
  saizPek                     double precision default 0,
  deskripsiPek                text,
  hargaSetiapPek              double precision,
  jumlahPekDihasilkan         integer,
  baki                        integer,
  arahanTambahan              text
);

create index if not exists idx_prabungkus_idUbat   on public.tblSenaraiPrabungkus(idUbat);
create index if not exists idx_prabungkus_namaUbat on public.tblSenaraiPrabungkus(namaUbat);
create index if not exists idx_prabungkus_tarikh   on public.tblSenaraiPrabungkus(tarikh);
create unique index if not exists idx_prabungkus_idUbat_idPrabungkus
  on public.tblSenaraiPrabungkus(idUbat, idPrabungkus);

-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- SECTION 2: uds schema (mirrors labeluds.db)
-- NOTE: LuputParseNote deliberately DROPPED (approved deviation)
-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

create schema if not exists uds;

-- Reset tables (reverse FK order) for clean re-runs.
drop table if exists uds.tblRekodLabel cascade;
drop table if exists uds.tblNamaUbat cascade;

create table if not exists uds.tblNamaUbat (
  "ID"        bigint generated by default as identity primary key,
  "Nama"      varchar(250) not null,
  "Kekuatan"  text
);

create table if not exists uds.tblRekodLabel (
  "ID"              bigint generated by default as identity primary key,
  "Tarikh"          text not null,             -- 'YYYY-MM-DD'
  "Rujukan"         text not null unique,      -- 'UDS-NNNN/YY'
  "NamaUbat"        text not null,             -- denormalized, uppercased
  "Kekuatan"        text,
  "Kelompok"        text not null,
  "Luput"           text not null,             -- display format (MM/YY etc.)
  "Kuantiti"        integer not null,
  "Penyedia"        text not null,
  "LuputNormalized" text,                      -- ISO 'YYYY-MM-DD' or NULL
  "NamaUbatID"      bigint references uds.tblNamaUbat("ID")   -- soft ref
);

create index if not exists idx_uds_rekodlabel_tarikh on uds.tblRekodLabel("Tarikh");
create index if not exists idx_uds_rekodlabel_namauBat on uds.tblRekodLabel("NamaUbat");

-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- SECTION 3: auth rate-limit table
-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

create table if not exists public.tblAuthAttempts (
  fingerprint text primary key,
  attempt_count integer not null default 0,
  locked_until text,           -- ISO timestamp or null
  updated_at text not null default to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
);

-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- SECTION 4: RLS policies
-- Single shared password model. Core tables fully open (matching
-- original: all pages except Tetapan are public). Tetapan-sensitive
-- tables gate WRITES behind app.password_verified.
-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

alter table public.tblJenisLabel        enable row level security;
alter table public.tblJenisWorksheet    enable row level security;
alter table public.tblKategoriUbat      enable row level security;
alter table public.tblUnitSKU           enable row level security;
alter table public.tblUnitPKU           enable row level security;
alter table public.tblSystemSettings    enable row level security;
alter table public.tblColorSchemes      enable row level security;
alter table public.tblSenaraiUbat       enable row level security;
alter table public.tblSenaraiPrabungkus enable row level security;
alter table uds.tblNamaUbat             enable row level security;
alter table uds.tblRekodLabel           enable row level security;
alter table public.tblAuthAttempts      enable row level security;

-- Core tables: full access for anon + authenticated
-- (matching original: all pages except Tetapan are public, no login)
drop policy if exists "app_users_full_access_jenislabel" on public.tblJenisLabel;
create policy "app_users_full_access_jenislabel" on public.tblJenisLabel
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "app_users_full_access_jenisworksheet" on public.tblJenisWorksheet;
create policy "app_users_full_access_jenisworksheet" on public.tblJenisWorksheet
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "app_users_full_access_kategori" on public.tblKategoriUbat;
create policy "app_users_full_access_kategori" on public.tblKategoriUbat
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "app_users_full_access_unitsku" on public.tblUnitSKU;
create policy "app_users_full_access_unitsku" on public.tblUnitSKU
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "app_users_full_access_unitpku" on public.tblUnitPKU;
create policy "app_users_full_access_unitpku" on public.tblUnitPKU
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "app_users_full_access_ubat" on public.tblSenaraiUbat;
create policy "app_users_full_access_ubat" on public.tblSenaraiUbat
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "app_users_full_access_prabungkus" on public.tblSenaraiPrabungkus;
create policy "app_users_full_access_prabungkus" on public.tblSenaraiPrabungkus
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "uds_full_access_namauBat" on uds.tblNamaUbat;
create policy "uds_full_access_namauBat" on uds.tblNamaUbat
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "uds_full_access_rekodlabel" on uds.tblRekodLabel;
create policy "uds_full_access_rekodlabel" on uds.tblRekodLabel
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "auth_attempts_app" on public.tblAuthAttempts;
create policy "auth_attempts_app" on public.tblAuthAttempts
  for all to anon, authenticated using (true) with check (true);

-- Tetapan-sensitive tables: reads open to all, writes gated behind password
drop policy if exists "settings_read" on public.tblSystemSettings;
create policy "settings_read" on public.tblSystemSettings
  for select to anon, authenticated using (true);

drop policy if exists "settings_write" on public.tblSystemSettings;
create policy "settings_write" on public.tblSystemSettings
  for all to anon, authenticated
  using (pg_catalog.current_setting('app.password_verified', true) = 'true')
  with check (pg_catalog.current_setting('app.password_verified', true) = 'true');

drop policy if exists "color_schemes_read" on public.tblColorSchemes;
create policy "color_schemes_read" on public.tblColorSchemes
  for select to anon, authenticated using (true);

drop policy if exists "color_schemes_write" on public.tblColorSchemes;
create policy "color_schemes_write" on public.tblColorSchemes
  for all to anon, authenticated
  using (pg_catalog.current_setting('app.password_verified', true) = 'true')
  with check (pg_catalog.current_setting('app.password_verified', true) = 'true');

-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- SECTION 5: seed data (lookups + defaults)
-- Running numbers are year-scoped (approved deviation): default 1.
-- admin_password placeholder replaced by seed.ts / migrate script.
-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

-- tblJenisLabel (label template types)
delete from public.tblJenisLabel;
insert into public.tblJenisLabel (deskripsiLabel, namaFail) values
  ('Tablet',                'label_tablet.docx'),
  ('Kapsul',                'label_kapsul.docx'),
  ('Suspensi',              'label_suspensi.docx'),
  ('Salap',                 'label_salap.docx'),
  ('Krim',                  'label_krim.docx'),
  ('Losion',                'label_losion.docx'),
  ('Titisan Mata',          'label_titisan_mata.docx'),
  ('Titisan Telinga',       'label_titisan_telinga.docx'),
  ('Titisan Hidung',        'label_titisan_hidung.docx'),
  ('Semburan Hidung',       'label_semburan_hidung.docx'),
  ('Semburan Mulut',        'label_semburan_mulut.docx'),
  ('Suntikan',              'label_suntikan.docx'),
  ('Infusi',                'label_infusi.docx'),
  ('Ubat Gigi',             'label_ubat_gigi.docx'),
  ('Gargle',                'label_gargle.docx'),
  ('Suppositori',           'label_suppositori.docx'),
  ('Pes',                   'label_pes.docx'),
  ('Gel',                   'label_gel.docx'),
  ('Sirap',                 'label_sirap.docx'),
  ('Emulsi',                'label_emulsi.docx'),
  ('Serbuk',                'label_serbuk.docx'),
  ('Air',                   'label_air.docx'),
  ('Aerosol',               'label_aerosol.docx'),
  ('Penyelesaian',          'label_penyelesaian.docx'),
  ('Penyelesaian Ubat',     'label_penyelesaian_ubat.docx'),
  ('Penyedut',              'label_penyedut.docx'),
  ('Penyembur',             'label_penyembur.docx'),
  ('Pengesan',              'label_pengesan.docx'),
  ('Pembasuh',              'label_pembasuh.docx'),
  ('Pencuci',               'label_pencuci.docx'),
  ('Losyen',                'label_losyen.docx'),
  ('Penyapu',               'label_penyapu.docx'),
  ('Penghalau',             'label_penghalau.docx');

-- tblJenisWorksheet (worksheet template types)
delete from public.tblJenisWorksheet;
insert into public.tblJenisWorksheet (deskripsiWorksheet, namaFail) values
  ('Umum', 'Kertas Kerja - Umum.docx');

-- tblKategoriUbat (prepack categories with prefix)
delete from public.tblKategoriUbat;
insert into public.tblKategoriUbat (nama, prefix) values
  ('Tablet/T/I', 'T'),
  ('Internal/E', 'I'),
  ('Eksternal/E', 'E');

-- tblUnitSKU
delete from public.tblUnitSKU;
insert into public.tblUnitSKU (nama) values
  ('Tablet'),
  ('Kapsul'),
  ('Botol'),
  ('Tiub'),
  ('Pek'),
  ('Ampul'),
  ('Sachet');

-- tblUnitPKU
delete from public.tblUnitPKU;
insert into public.tblUnitPKU (nama) values
  ('Pek'),
  ('Botol'),
  ('Tiub');

-- tblSystemSettings (defaults; admin_password replaced by seed script)
insert into public.tblSystemSettings (settingKey, settingValue) values
  ('admin_password', '__ADMIN_HASH__'),
  ('color_scheme',   'light')
on conflict (settingKey) do nothing;

-- tblColorSchemes: default built-in (light / Bold Wikipedia)
insert into public.tblColorSchemes (schemeId, name, colors, css, isBuiltIn) values
  ('light', 'Light', '["#ffffff","#f4f4f5","#e4e4e7","#1f6feb","#52525b"]', '{"--background":"hsl(0 0% 100%)","--foreground":"hsl(0 0% 15%)","--card":"hsl(0 0% 100%)","--card-foreground":"hsl(0 0% 15%)","--popover":"hsl(0 0% 100%)","--popover-foreground":"hsl(0 0% 15%)","--primary":"hsl(214 85% 45%)","--primary-foreground":"hsl(0 0% 100%)","--secondary":"hsl(210 20% 96%)","--secondary-foreground":"hsl(0 0% 15%)","--muted":"hsl(0 0% 96%)","--muted-foreground":"hsl(0 0% 45%)","--accent":"hsl(214 85% 96%)","--accent-foreground":"hsl(214 85% 35%)","--destructive":"hsl(0 84% 44%)","--destructive-foreground":"hsl(0 0% 100%)","--border":"hsl(0 0% 82%)","--input":"hsl(0 0% 90%)","--ring":"hsl(214 85% 45%)","--chart-1":"hsl(214 85% 45%)","--chart-2":"hsl(160 84% 39%)","--chart-3":"hsl(30 95% 45%)","--chart-4":"hsl(280 75% 55%)","--chart-5":"hsl(340 85% 50%)","--sidebar":"hsl(0 0% 98%)","--sidebar-foreground":"hsl(0 0% 25%)","--sidebar-primary":"hsl(214 85% 45%)","--sidebar-primary-foreground":"hsl(0 0% 100%)","--sidebar-accent":"hsl(214 40% 94%)","--sidebar-accent-foreground":"hsl(214 85% 35%)","--sidebar-border":"hsl(0 0% 90%)","--sidebar-ring":"hsl(214 85% 45%)","--radius":"0.125rem","--font-sans":"\\"Inter\\", \\"Segoe UI\\", \\"Helvetica Neue\\", sans-serif","--font-mono":"\\"Geist Mono\\", monospace","--shadow-color":"rgba(0, 0, 0, 0.1)","--shadow-opacity":"0.05","--shadow-blur":"4px","--shadow-spread":"0px","--shadow-offset-x":"0px","--shadow-offset-y":"1px","--letter-spacing":"0.0125em"}', 1)
on conflict (schemeId) do nothing;

-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- SECTION 6: transactional ID reservation (RPC functions)
-- Year-scoped running numbers + atomic reserve+insert via SELECT FOR UPDATE.
-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

-- Prepack counter helpers
create or replace function public.lock_prepack_counter(p_year integer)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_value integer;
begin
  if exists (
    select 1 from public.tblsystemsettings
    where settingkey = 'running_number_' || p_year
  ) then
    select settingvalue::integer into v_value
    from public.tblsystemsettings
    where settingkey = 'running_number_' || p_year
    for update;
  else
    insert into public.tblsystemsettings (settingkey, settingvalue)
    values ('running_number_' || p_year, '1')
    on conflict (settingkey) do nothing;
    v_value := 1;
  end if;
  return v_value;
end;
$$;

create or replace function public.bump_prepack_counter(p_year integer, p_next integer)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new integer;
begin
  insert into public.tblsystemsettings (settingkey, settingvalue)
  values ('running_number_' || p_year, p_next::text)
  on conflict (settingkey) do update
    set settingvalue = greatest(
      public.tblsystemsettings.settingvalue::integer, p_next
    )::text
  returning settingvalue::integer into v_new;
  return v_new;
end;
$$;

-- UDS counter helpers
create or replace function public.lock_uds_counter(p_year integer)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_value integer;
begin
  if exists (
    select 1 from public.tblsystemsettings
    where settingkey = 'running_number_uds_' || p_year
  ) then
    select settingvalue::integer into v_value
    from public.tblsystemsettings
    where settingkey = 'running_number_uds_' || p_year
    for update;
  else
    insert into public.tblsystemsettings (settingkey, settingvalue)
    values ('running_number_uds_' || p_year, '1')
    on conflict (settingkey) do nothing;
    v_value := 1;
  end if;
  return v_value;
end;
$$;

create or replace function public.bump_uds_counter(p_year integer, p_next integer)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new integer;
begin
  insert into public.tblsystemsettings (settingkey, settingvalue)
  values ('running_number_uds_' || p_year, p_next::text)
  on conflict (settingkey) do update
    set settingvalue = greatest(
      public.tblsystemsettings.settingvalue::integer, p_next
    )::text
  returning settingvalue::integer into v_new;
  return v_new;
end;
$$;

-- Prepack: atomic create with reserved PP-NNNN/YY-X
create or replace function public.create_prabungkus(
  p_kategori          text,
  p_tarikh            text,
  p_ubat              jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_prefix  text;
  v_year    integer;
  v_frag    text;
  v_counter integer;
  v_candidate integer;
  v_id      text;
  v_next    integer;
  v_row     jsonb;
begin
  select coalesce(prefix, 'X') into v_prefix
    from public.tblkategoriubat
    where nama = p_kategori;
  if v_prefix is null or v_prefix = '' then
    v_prefix := 'X';
  end if;
  v_prefix := upper(trim(v_prefix));

  v_year := coalesce(substring(p_tarikh from 1 for 4)::integer, extract(year from now())::integer);
  v_frag := lpad((v_year % 100)::text, 2, '0');

  select lock_prepack_counter(v_year) into v_counter;

  v_candidate := v_counter;
  v_next := v_counter;
  loop
    v_id := 'PP-' || lpad(v_candidate::text, 4, '0') || '/' || v_frag || '-' || v_prefix;
    if not exists (
      select 1 from public.tblsenaraiprabungkus where idprabungkus = v_id
    ) then
      exit;
    end if;
    v_candidate := v_candidate + 1;
    v_next := greatest(v_next, v_candidate);
  end loop;

  insert into public.tblsenaraiprabungkus (
    idubat, namaubat, tarikh, idprabungkus, namadagangan,
    nomborkelompok, tarikhluputasal, tarikhluputbaharu, pengilang,
    nombormal, kuantitiuntukdiprabungkus, saizpek, deskripsipek,
    hargasetiappek, jumlahpekdihasilkan, baki, arahanTambahan
  )
  values (
    (p_ubat->>'idUbat')::bigint,
    coalesce(p_ubat->>'namaUbat', ''),
    p_tarikh,
    v_id,
    nullif(p_ubat->>'namaDagangan', ''),
    nullif(p_ubat->>'nomborKelompok', ''),
    nullif(p_ubat->>'tarikhLuputAsal', ''),
    nullif(p_ubat->>'tarikhLuputBaharu', ''),
    nullif(p_ubat->>'pengilang', ''),
    nullif(p_ubat->>'nomborMAL', ''),
    nullif((p_ubat->>'kuantitiUntukDiprabungkus')::integer, null),
    coalesce((p_ubat->>'saizPek')::double precision, 0),
    nullif(p_ubat->>'deskripsiPek', ''),
    nullif((p_ubat->>'hargaSetiapPek')::double precision, null),
    nullif((p_ubat->>'jumlahPekDihasilkan')::integer, null),
    nullif((p_ubat->>'baki')::integer, null),
    nullif(p_ubat->>'arahanTambahan', '')
  );

  v_next := v_next + 1;
  perform bump_prepack_counter(v_year, v_next);

  select row_to_json(t) into v_row from (
    select "ID", idubat, namaubat, tarikh, "idPrabungkus", namadagangan,
      nomborkelompok, tarikhluputasal, tarikhluputbaharu, pengilang,
      nombormal, kuantitiuntukdiprabungkus, saizpek, deskripsipek,
      hargasetiappek, jumlahpekdihasilkan, baki, arahanTambahan
    from public.tblsenaraiprabungkus
    where "idPrabungkus" = v_id
  ) t;

  return v_row;
end;
$$;

-- Prepack: preview next ID (no reserve)
create or replace function public.preview_prepack_id(p_kategori text, p_tarikh text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_prefix text;
  v_year integer;
  v_frag text;
  v_counter integer;
  v_candidate integer;
  v_id text;
begin
  select coalesce(prefix, 'X') into v_prefix
    from public.tblkategoriubat where nama = p_kategori;
  v_prefix := coalesce(upper(trim(v_prefix)), 'X');
  if v_prefix = '' then v_prefix := 'X'; end if;

  v_year := coalesce(substring(p_tarikh from 1 for 4)::integer, extract(year from now())::integer);
  v_frag := lpad((v_year % 100)::text, 2, '0');

  select coalesce(settingvalue::integer, 1) into v_counter
    from public.tblsystemsettings
    where settingkey = 'running_number_' || v_year;

  v_candidate := coalesce(v_counter, 1);
  loop
    v_id := 'PP-' || lpad(v_candidate::text, 4, '0') || '/' || v_frag || '-' || v_prefix;
    if not exists (select 1 from public.tblsenaraiprabungkus where idprabungkus = v_id) then
      return v_id;
    end if;
    v_candidate := v_candidate + 1;
  end loop;
end;
$$;

-- Highest used prepack running number for a given year (admin validation)
create or replace function public.highest_prepack_number(p_year integer)
returns integer
language sql
security definer
set search_path = public
as $$
  select coalesce(max(
    substring(idprabungkus from 4 for 4)::integer
  ), 0)
  from public.tblsenaraiprabungkus
  where idprabungkus ~ '^PP-[0-9]{4}/[0-9]{2}-'
    and substring(idprabungkus from 9 for 2) = lpad((p_year % 100)::text, 2, '0');
$$;

-- UDS: atomic create with reserved UDS-NNNN/YY
create or replace function public.create_uds_label(
  p_tarikh text,
  p_namaUbat text,
  p_kekuatan text,
  p_kelompok text,
  p_luput text,
  p_kuantiti integer,
  p_penyedia text,
  p_luputnormalized text,
  p_namaUbat_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_year integer;
  v_frag text;
  v_counter integer;
  v_candidate integer;
  v_id text;
  v_row jsonb;
begin
  v_year := coalesce(substring(p_tarikh from 1 for 4)::integer, extract(year from now())::integer);
  v_frag := lpad((v_year % 100)::text, 2, '0');

  select lock_uds_counter(v_year) into v_counter;
  v_candidate := v_counter;
  loop
    v_id := 'UDS-' || lpad(v_candidate::text, 4, '0') || '/' || v_frag;
    if not exists (select 1 from uds.tblrekodlabel where "Rujukan" = v_id) then
      exit;
    end if;
    v_candidate := v_candidate + 1;
  end loop;

  insert into uds.tblrekodlabel (
    "Tarikh", "Rujukan", "NamaUbat", "Kekuatan", "Kelompok",
    "Luput", "Kuantiti", "Penyedia", "LuputNormalized", "NamaUbatID"
  )
  values (
    p_tarikh, v_id, p_namaUbat, nullif(p_kekuatan, ''), p_kelompok,
    p_luput, p_kuantiti, p_penyedia, nullif(p_luputnormalized, ''), p_namaUbat_id
  );

  perform bump_uds_counter(v_year, v_counter + 1);

  select row_to_json(t) into v_row from (
    select "ID", "Tarikh", "Rujukan", "NamaUbat", "Kekuatan", "Kelompok",
      "Luput", "Kuantiti", "Penyedia", "LuputNormalized", "NamaUbatID"
    from uds.tblrekodlabel where "Rujukan" = v_id
  ) t;
  return v_row;
end;
$$;

-- UDS: preview next Rujukan (no reserve)
create or replace function public.preview_uds_rujukan(p_tarikh text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_year integer;
  v_frag text;
  v_counter integer;
  v_candidate integer;
  v_id text;
begin
  v_year := coalesce(substring(p_tarikh from 1 for 4)::integer, extract(year from now())::integer);
  v_frag := lpad((v_year % 100)::text, 2, '0');
  select coalesce(settingvalue::integer, 1) into v_counter
    from public.tblsystemsettings
    where settingkey = 'running_number_uds_' || v_year;
  v_candidate := coalesce(v_counter, 1);
  loop
    v_id := 'UDS-' || lpad(v_candidate::text, 4, '0') || '/' || v_frag;
    if not exists (select 1 from uds.tblrekodlabel where "Rujukan" = v_id) then
      return v_id;
    end if;
    v_candidate := v_candidate + 1;
  end loop;
end;
$$;

-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- SECTION 7: auth rate-limit RPC function
-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

create or replace function public.lock_auth_attempt(p_fingerprint text)
returns table (attempt_count integer, locked_until text)
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.tblauthattempts (fingerprint, attempt_count, locked_until)
  values (p_fingerprint, 0, null)
  on conflict (fingerprint) do nothing;
  return query
    select a.attempt_count::integer, a.locked_until::text
    from public.tblauthattempts a
    where a.fingerprint = p_fingerprint
    for update;
end;
$$;

-- ============================================================
-- End of consolidated schema
-- ============================================================

-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-- SECTION 8: privileges (GRANTs)
-- Tables created via raw SQL do not inherit Supabase's default
-- grants. The service_role (used by Server Actions + migration
-- scripts) and anon/authenticated (RLS) roles need explicit access.
-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

-- Row-level objects (tables, sequences, indexes)
grant usage on schema public to anon, authenticated, service_role;
grant usage on schema uds to anon, authenticated, service_role;

alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public grant all on sequences to anon, authenticated, service_role;
alter default privileges in schema public grant all on functions to anon, authenticated, service_role;
alter default privileges in schema uds grant all on tables to anon, authenticated, service_role;
alter default privileges in schema uds grant all on sequences to anon, authenticated, service_role;
alter default privileges in schema uds grant all on functions to anon, authenticated, service_role;

grant all on all tables in schema public to anon, authenticated, service_role;
grant all on all tables in schema uds to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;
grant all on all sequences in schema uds to anon, authenticated, service_role;
grant execute on all functions in schema public to anon, authenticated, service_role;
grant execute on all functions in schema uds to anon, authenticated, service_role;