-- ============================================================
-- Sistem Pengurusan Prabungkus Ubat — Modernization
-- PHASE 0 Migration 00002: uds schema (label system)
-- Mirrors labeluds.db (schema-faithful, additive-only)
-- NOTE: LuputParseNote deliberately DROPPED (approved deviation)
--
-- Idempotent: tables are dropped (reverse FK order) and recreated so
-- re-running this file always yields a clean, consistent schema.
-- ============================================================

create schema if not exists uds;

-- ---------- Reset tables (reverse FK order) for clean re-runs ----------

drop table if exists uds.tblRekodLabel;
drop table if exists uds.tblNamaUbat;

-- ---------- UDS medication names ----------

create table uds.tblNamaUbat (
  "ID"        bigint generated by default as identity primary key,
  "Nama"      varchar(250) not null,
  "Kekuatan"  text
);

-- ---------- UDS label records ----------

create table uds.tblRekodLabel (
  "ID"              bigint generated by default as identity primary key,
  "Tarikh"          text not null,             -- 'YYYY-MM-DD'
  "Rujukan"         text not null unique,      -- 'UDS-NNNN/YY'
  "NamaUbat"        text not null,             -- denormalized, uppercased
  "Kekuatan"        text,
  "Kelompok"        text not null,
  "Luput"           text not null,             -- display format (MM/YY etc.)
  "Kuantiti"        integer not null,
  "Penyedia"        text not null,
  "LuputNormalized" text,                      -- ISO 'YYYY-MM-DD' or NULL
  "NamaUbatID"      bigint references uds.tblNamaUbat("ID")   -- soft ref
);

-- ---------- Additive indexes (safe, no fidelity change) ----------

create index if not exists idx_uds_rekodlabel_tarikh on uds.tblRekodLabel("Tarikh");
create index if not exists idx_uds_rekodlabel_namauBat on uds.tblRekodLabel("NamaUbat");