-- ============================================================
-- Sistem Pengurusan Prabungkus Ubat — Modernization
-- PHASE 0 Migration 00001: public schema (main system)
-- Mirrors prepack_webapp.db (schema-faithful, additive-only)
--
-- Idempotent: tables are dropped (reverse FK order) and recreated so
-- re-running this file always yields a clean, consistent schema.
-- ============================================================

-- ---------- Reset tables (reverse FK order) for clean re-runs ----------

drop table if exists public.tblSenaraiPrabungkus;
drop table if exists public.tblSenaraiUbat;
drop table if exists public.tblColorSchemes;
drop table if exists public.tblSystemSettings;
drop table if exists public.tblJenisWorksheet;
drop table if exists public.tblJenisLabel;
drop table if exists public.tblKategoriUbat;
drop table if exists public.tblUnitSKU;
drop table if exists public.tblUnitPKU;

-- ---------- Lookup / reference tables ----------

create table public.tblJenisLabel (
  "ID"             bigint generated by default as identity primary key,
  deskripsiLabel   text not null,
  namaFail         text not null
);

create table public.tblJenisWorksheet (
  "ID"                 bigint generated by default as identity primary key,
  deskripsiWorksheet   text not null,
  namaFail             text not null
);

create table public.tblKategoriUbat (
  "ID"     bigint generated by default as identity primary key,
  nama     text not null,
  prefix   text not null
);

create table public.tblUnitSKU (
  "ID"   bigint generated by default as identity primary key,
  nama   text not null
);

create table public.tblUnitPKU (
  "ID"   bigint generated by default as identity primary key,
  nama   text not null
);

create table public.tblSystemSettings (
  settingKey    text primary key,
  settingValue  text not null
);

create table public.tblColorSchemes (
  "ID"        bigint generated by default as identity primary key,
  schemeId    text not null unique,
  name        text not null,
  colors      text not null,          -- JSON array of 5 hex colors
  css         text not null,          -- JSON object of CSS variables
  isBuiltIn   integer default 0
);

-- ---------- Medication master ----------

create table public.tblSenaraiUbat (
  "ID"                  bigint generated by default as identity primary key,
  deskripsiPrabungkus   text,
  namaUbat              text not null,
  namaDagangan          text,
  kategoriUbat          text not null,
  unitSKU               text,
  unitPKU               text,
  harga                 double precision,
  saizPek               double precision default 0,
  pengilang             text,
  nomborMAL             text,
  arahanTambahan        text,
  jangkaHayat           integer default 0,
  jenisLabel            bigint references public.tblJenisLabel("ID"),
  jenisWorksheet        bigint references public.tblJenisWorksheet("ID")
);

create index if not exists idx_ubat_kategori on public.tblSenaraiUbat(kategoriUbat);

-- ---------- Prepack records ----------

create table public.tblSenaraiPrabungkus (
  "ID"                        bigint generated by default as identity primary key,
  idUbat                      bigint,                    -- soft ref (no FK, matching original)
  namaUbat                    text not null,             -- denormalized snapshot
  tarikh                      text not null,             -- 'YYYY-MM-DD'
  idPrabungkus                text not null unique,      -- 'PP-NNNN/YY-X'
  namaDagangan                text,
  nomborKelompok              text,
  tarikhLuputAsal             text,
  tarikhLuputBaharu           text,
  pengilang                   text,
  nomborMAL                   text,
  kuantitiUntukDiprabungkus   integer,
  saizPek                     double precision default 0,
  deskripsiPek                text,
  hargaSetiapPek              double precision,
  jumlahPekDihasilkan         integer,
  baki                        integer,
  arahanTambahan              text
);

create index if not exists idx_prabungkus_idUbat   on public.tblSenaraiPrabungkus(idUbat);
create index if not exists idx_prabungkus_namaUbat on public.tblSenaraiPrabungkus(namaUbat);
create index if not exists idx_prabungkus_tarikh   on public.tblSenaraiPrabungkus(tarikh);

-- Additive safety index (safe, no fidelity change)
create unique index if not exists idx_prabungkus_idUbat_idPrabungkus
  on public.tblSenaraiPrabungkus(idUbat, idPrabungkus);